### ISSUE TITLE
サーバ側 - ログの導入

### ISSUE THREAD

**Issue by gBenkyou1** [gBenkyous/inTime#10]
サーバ側へログを吐き出す必要がある決める内容としては下記である。

- 吐き出す内容
- ログを吐き出すためのツール

**Comment by haruki256** [comment]
一応gin のログに関するやつ
https://gin-gonic.com/ja/docs/examples/write-log/
https://gin-gonic.com/ja/docs/examples/controlling-log-output-coloring/

**Comment by haruki256** [comment]
https://github.com/gBenkyous/inTime/tree/feature/ha_log_dev
# エラーメッセージが出る奴。 上がいじったブランチです。

https://medium.com/@basakabhijoy/global-exception-handling-in-gin-11d7ab17c43c
https://gin-gonic.com/zh-tw/docs/examples/using-middleware/

**Comment by haruki256** [comment]
ログの変更

https://synamon.hatenablog.com/entry/2022/09/28/180048
https://github.com/gin-contrib/logger

上手いこと組み合わせてerrorを表示してもらえると助かりまする。

**Comment by haruki256** [comment]
ブランチを送ったのですが、ミドルウェアにログの処理いれれば行けそうです。
https://golangexample.com/gin-error-handling-middleware-is-a-middleware-for-the-popular-gin-framework/

**Comment by haruki256** [comment]
ゴール
ログファイルは１つ
内容
- アクセスログ
- エラーログ

**Comment by gonzaresu-sengoku** [comment]
エラーログ
https://zenn.dev/nekoshita/articles/097e00c6d3d1c9

アクセスログ
https://qiita.com/gimKondo/items/cdd5d3cfee7d551efce8

**Comment by gonzaresu-sengoku** [comment]
■メモ
・アクセスログは共通関数化させる
・エラーログのトレースの件は引き続き調査
