### ISSUE TITLE
サーバ側 - テストの導入

### ISSUE THREAD

**Issue by haruki256** [gBenkyous/inTime#11]
サーバ側のテストの導入

決めること

- テスト方法
- テストツール

**Comment by haruki256** [comment]
@watabusi 
参考記事
https://eltonminetto.dev/en/post/2019-12-19-gomock/

**Comment by haruki256** [comment]
一応ginに関するテストもあったので共有です。
https://gin-gonic.com/ja/docs/testing/

**Comment by haruki256** [comment]
moc調査後に閉める

**Comment by haruki256** [comment]
わたべさんへ
テストファイルをどこに作るか決めていただけますでしょうか

**Comment by watabusi** [comment]
https://github.com/gBenkyous/wiki/blob/main/inTime/ALL/%E5%9F%BA%E7%A4%8E%E5%AE%9A%E7%BE%A9/%E3%83%86%E3%82%B9%E3%83%88%E5%86%85%E5%AE%B9/%E8%A6%8F%E5%89%87.txt

ファイルの配置・名称について

**Comment by watabusi** [comment]
ソース配置
https://github.com/gBenkyous/inTime/tree/ex/go_test_sample

**Comment by haruki256** [comment]
https://github.com/gBenkyous/inTime/tree/ex/go_test_sample
