### ISSUE TITLE
docker image の減量

### ISSUE THREAD

**Issue by doranko** [gBenkyous/inTime#20]
# 概要

マルチステージビルドにすることでイメージサイズを削減する

# 修正案

- 開発用、ビルド用、本番配置用の 3 つのステージに分ける
- 開発用は golang:[version]-alpine をベースイメージに使い、make は使えるようにする
- 本番配置用は scratch イメージにビルド結果の実行ファイルを配置
    - 参考：[dockerのscratchイメージでgolangのWebアプリを動かす](https://qiita.com/4486/items/915e9e4c77f012c365ff)
- 本番配置用サービスには docker-compose.yml 内で profiles を記載しておくことで普段は起動しないようにする
    - 参考：[Compose で プロフィールを使う](https://docs.docker.jp/compose/profiles.html#compose)

ざっくりこんな感じ
```Dockerfile
# 開発用
FROM golang:1.19-alpine AS dev
RUN 〜
# ビルド用
FROM golang:1.19-alpine AS build
RUN ビルド実行コマンド
# 本番配置用
FROM scratch AS prod
COPY --from build 実行ファイル /bin/app
ENTRYPOINT ["/bin/app"]
```

```docker-compose.yml
version: "3.4"
services:
    server-dev:
        build:
            context: ./server
            target: dev
        image: server-dev
    server-prod:
        build:
            context: ./server
            target: prod
        image: server-prod
        profiles:
            - prod
```

# 修正後にどうなるか

- 開発時は特に変更なし
- 本番に配置する際は本番配置用イメージを利用する

# なぜわざわざこんなことを？

- レンタルサーバにデプロイするなら容量は小さい方が安く済む
- そもそもサイズが大きいとデメリットはあっても利点は無い
- https://speakerdeck.com/stormcat24/oqian-falsedockerimezihamadazhong-i

**Comment by haruki256** [comment]
こちらについてはdockerを本番環境にて利用する場合には行いたいです！
ただ、本番環境でdockerを利用するかどうかを話し合っていなかったため次回の勉強会の議題に上げたいです。

**Comment by haruki256** [comment]
ただ、本番環境での利用にかかわらずプルリクエストの内容の一部は反映させたいので要相談したいです。

**Comment by haruki256** [comment]
実行ファイルを置く形式に決定したためこちらは適用しない
