### ISSUE TITLE
ginの設定における不具合修正

### ISSUE THREAD

**Issue by doranko** [gBenkyous/inTime#22]
https://github.com/gBenkyous/inTime/blob/feature/reduce-image-size/server/cmd/intime/main.go#L45

ホストからコンテナにアクセスする際、IP部分を記述してると繋がらないっぽい。
原因は不明。
ポート番号のみ、もしくは8080のままで良いなら引数自体消してしまう。

r.Run()
 -> windowsから接続 可
r.Run(“:8080”)
 -> windowsから接続 可
r.Run(“localhost:8080”)
 -> windowsから接続 不可、コンテナ内からの curl は通る

**Comment by haruki256** [comment]
とても良いかと！

**Comment by haruki256** [comment]
全体確認の結果問題なし

**Comment by haruki256** [comment]
マージ完了したためクローズ
