### ISSUE TITLE
ボードに関しての仕様確認

### ISSUE THREAD

**Issue by haruki256** [gBenkyous/inTime#30]

**Comment by haruki256** [comment]
バックログに合わせて修正予定

**Comment by watabusi** [comment]
https://github.com/gBenkyous/wiki/blob/main/inTime/ALL/%E4%BB%95%E6%A7%98%E5%AE%9A%E7%BE%A9/%E3%83%9C%E3%83%BC%E3%83%89/%E6%B4%97%E3%81%84%E5%87%BA%E3%81%97.txt
レビュー待ち
