### ISSUE TITLE
変更履歴(最新の更新)の仕様確認

### ISSUE THREAD

**Issue by haruki256** [gBenkyous/inTime#31]

**Comment by gonzaresu-sengoku** [comment]
https://github.com/gBenkyous/wiki/blob/main/inTime/ALL/%E4%BB%95%E6%A7%98%E5%AE%9A%E7%BE%A9/%E5%A4%89%E6%9B%B4%E5%B1%A5%E6%AD%B4(%E3%83%9B%E3%83%BC%E3%83%A0)/%E6%B4%97%E3%81%84%E5%87%BA%E3%81%97.txt

**Comment by haruki256** [comment]
深堀時には別イシュー作成
