### ISSUE TITLE
Checkstyle の導入について

### ISSUE THREAD

**Issue by haruki256** [gBenkyous/inTime#35]
コーディングルールのチェック用のツールを導入する。
プラグインの導入

**Comment by gonzaresu-sengoku** [comment]
コードフォーマッターによるコード自動整形させることも検討

**Comment by doranko** [comment]
https://devlights.hatenablog.com/entry/2019/08/15/060851

**Comment by haruki256** [comment]
開発に入る前には決めておきたい。

**Comment by haruki256** [comment]
gofmtを利用する。
vscなどに設定しておく。
