### ISSUE TITLE
テスト資料作成

### ISSUE THREAD

**Issue by haruki256** [gBenkyous/inTime#45]
テストソース作成の手順など

**Comment by watabusi** [comment]
https://github.com/gBenkyous/wiki/blob/main/inTime/ALL/%E5%9F%BA%E7%A4%8E%E5%AE%9A%E7%BE%A9/%E3%83%86%E3%82%B9%E3%83%88%E5%86%85%E5%AE%B9/%E3%83%86%E3%82%B9%E3%83%88%E8%B3%87%E6%96%99(go).txt
作成途中
