### ISSUE TITLE
テスト駆動開発用の資料を作成する。

### ISSUE THREAD

**Issue by haruki256** [gBenkyous/inTime#49]

**Comment by haruki256** [comment]
根本、本間
レビュー、東さん、かいちゃん

**Comment by haruki256** [comment]
やってもらうこと
- テスト駆動開発の情報を整えること
  - メリットデメリット、注意点、ポイント、活用法など
- テスト駆動開発を行う上でのルールぎめ
  - 実際の開発で使うためのルールなど
- その他実際に活用していく上で決めることや、全体で把握しておくべきことなどあれば宜しくお願い致します。

**Comment by haruki256** [comment]
@doranko @gonzaresu-sengoku 

記事作ったのでこの情報を元に断捨離してもらえればと
なんか補足必要な部分あれば行ってください。

https://bubbly-shingle-859.notion.site/17f03f2dd73a4bfe976d57e6b5bb2a6d

**Comment by haruki256** [comment]
基本的にはお二人で対応いただきたいですが、時間も合わないと思うので、個人個人で相手の顔色を伺わずバッサリ必要部分の修正削除、迷うべき点などはコメントを残すなどで勧めていただければと思います。
共有した記事は元用として残し、下記のリンクの記事で直接変更いただかればと思います。
https://bubbly-shingle-859.notion.site/e631045833914ec482c6a298369b9b12

**Comment by doranko** [comment]
記事修正しました
