### ISSUE TITLE
ORM選定

### ISSUE THREAD

**Issue by doranko** [gBenkyous/inTime#55]

**Comment by doranko** [comment]
# ent

- 自動生成されるファイルが多いが、/ent 配下にまとまるので意識することはない
- /ent/schema 配下にテーブル定義を記載
- SQL は自動生成される (= DB の種別は意識せずに済む)
- 複雑な SQL を実行する場合は modify 機能で対応できるが生 SQL より煩雑になる
    - https://entgo.io/ja/docs/feature-flags/#custom-sql-modifiers
- テーブル結合は Join メソッドで対応できる？要確認
  - https://entgo.io/ja/docs/feature-flags/#custom-sql-modifiers

**Comment by gonzaresu-sengoku** [comment]
# GORM

- 未導入
- 「Raw SQL」でSQL文をかけそう(joinができるか確認しないといけない)
    - 参考記事：https://gorm.io/docs/sql_builder.html
- SQL文かかなくても開発可能
- GORMのこと調べたけど忘れた！
-

**Comment by watabusi** [comment]
# sqlc
- 未導入
- sqlから.goのテーブル定義やクエリを生成
- 複雑なクエリもsqlから生成できるのでコーディングで面倒なことにはなりづらい印象
  - https://debimate.jp/2022/06/25/%E3%80%90golang%E3%80%91sqlc%E3%82%B3%E3%83%9E%E3%83%B3%E3%83%89%E3%81%A7%E3%80%8Csql%E3%82%AF%E3%82%A8%E3%83%AA%E3%81%8B%E3%82%89%E5%9E%8B%E5%AE%89%E5%85%A8%E3%81%AAgo%E3%82%B3%E3%83%BC%E3%83%89/

**Comment by haruki256** [comment]
entで行う　渡部さんにも確認お願いする。

**Comment by gonzaresu-sengoku** [comment]
渡部社長に承認いただきました。
