### ISSUE TITLE
クライアント側のパッケージ構成決める

### ISSUE THREAD

**Issue by haruki256** [gBenkyous/inTime#60]

**Comment by haruki256** [comment]
reactパッケージ構成
https://technostacks.com/blog/react-best-practices/

https://ja.legacy.reactjs.org/docs/faq-structure.html
サーバサイド参考にしてもいいのかぁ
https://tech.locaop.jp/entry/2023/02/17/121250

https://qiita.com/Sotq_17/items/7c7ab9880597336b3ee5#%E5%85%AC%E5%BC%8F%E3%81%A7%E3%81%AE%E6%89%B1%E3%81%84%E3%81%AFeyes

https://tech-blog.rakus.co.jp/entry/20230208/frontend

https://blog.microcms.io/web-frontend-architecture/

https://qiita.com/70ki8suda/items/7b720217c9b1b4855e99

https://zenn.dev/kichion/articles/fddf0eb35ffa2a

**Comment by doranko** [comment]
前提として申し訳ないですが私は現状のフロント側がどのような状態になっているのか確認できておらず、**どの機能がどのコードによって動作しているのか**を把握していません。
なので1機能ごとにどのようなパーツ (ソースコード) が必要になるのかを理解していないので議論にまともに参加できないです。
その上でのコメントです。

https://qiita.com/10mi8o/items/4fdb595f68606bceccfd

機能ごとに管理する re-ducks パターンが分かりやすそう。

また、MUI導入により大量にコンポーネントが増えていると思います。
ちらっと覗いた感じMUI利用時に必要なテンプレートファイルかなと思いましたのでそれはそれで components ディレクトリを分けないと混乱を生むように見えます。

**Comment by gonzaresu-sengoku** [comment]
別チームのパッケージ構成みてみました！

components：サービスごとにフォルダが切られていて、その中でページごとにファイルがわかれている。HTMLが記載
config：各環境envファイルや定数など
containers：よくわからん！ReactとReduxを連携するところ？
reducks：reducks関連のファイルが入っている。
router：アプリのルーティング設定が入っている。ページ間の遷移制御だったり。
styles：CSS関連。
utils：共通関数など。

**Comment by haruki256** [comment]
基本的にアルゴンと同じにするが、アルゴンはyarn管理にする。

**Comment by haruki256** [comment]
わんちゃん、アルゴンダッシュボード捨てて、MUI単体のテンプレートに変更するかも
