### ISSUE TITLE
クライアント側 - Axios（API連携に必要）の検討・導入

### ISSUE THREAD

**Issue by gonzaresu-sengoku** [gBenkyous/inTime#62]

**Comment by haruki256** [comment]
fetch関数かaxiosを使うか
https://taidanahibi.com/react/fetch-axios/

ゆーてそこまでaxiosのメリット感じなかったのでなくてもいいかなーと

次回以降のアプリケーションで使いたい場合に使えばいいかと

あとaxiosの場合CORSエラー起こる可能性もあるらしく一旦フェッチ関数でいいかなと

**Comment by haruki256** [comment]
fetch関数を使うことで了承
