### ISSUE TITLE
Reactのコードの繋がり部分は把握会の実施

### ISSUE THREAD

**Issue by haruki256** [gBenkyous/inTime#65]

**Comment by doranko** [comment]
reduxの学習(& 導入) はいったん後回し気味の感覚で。
stateの管理は React 自身の hook でやってみる？

**Comment by doranko** [comment]
本間君の資料がそろい次第、日程調整 (1日がっつり or 毎週土曜の勉強会の一部の時間でちょこちょこ など)

**Comment by haruki256** [comment]
react自体の基礎勉強会を最初に行う

**Comment by haruki256** [comment]
OK
