### ISSUE TITLE
ログの出力先の指定方法について

### ISSUE THREAD

**Issue by haruki256** [gBenkyous/inTime#66]
相対パスはミスを起こしやすいので絶対パス指定のほうが良いかと思いますが如何でしょうか。
また、TODO ということですが決定を先延ばしにする必要はないかと思いますので本レビュー中に議論・決定してしまってよいと思います。

_Originally posted by @doranko in https://github.com/gBenkyous/inTime/pull/59#discussion_r1257213466_

**Comment by haruki256** [comment]
僕も絶対パスでいいと思います。

**Comment by gonzaresu-sengoku** [comment]
ありがとうございます！！絶対パス指定が良いと思います！
例：/var/log/go/application.log

**Comment by gonzaresu-sengoku** [comment]
東さん参考例：/log/intime/api/XXX.log

**Comment by haruki256** [comment]
僕は
log/apps/intime/api....がすきです。

**Comment by watabusi** [comment]
方針：絶対パス指定

出力先について
dockerのコンテナ上で出力しているので、どこに配置しようがクライアント側とか他アプリとは被らない、またcomposeとかで出力したログの永続化しないといけない
そんなにログの出力先こだわる必要ない
