### ISSUE TITLE
環境の見直しと統一

### ISSUE THREAD

**Issue by haruki256** [gBenkyous/inTime#96]

**Comment by haruki256** [comment]
どのOSで環境で、やるか
コマンドラインなのか、vscプラグインないから立ち上げるのかなど。

**Comment by watabusi** [comment]
・規定のディストリビューション： Ubuntu
・立ち上げ方法(変更)：プロジェクトごとにショートカット用意し、「コンテナで再度開く」から開くと楽
　・https://qiita.com/doranko/items/00911f42d25ae5f51e10
　・自分がやってた「VSC上でWSL接続→コンテナで開く」の流れは廃止

**Comment by haruki256** [comment]
導入手順
- wsl有効化(docker導入のため）
- ubuntuインストール
- docker インストール
- docker 導入後 
- Ubuntuに対象プロジェクト配置（今回はintime）
- wsl -l でlinux用windowsサブシステムディストリビューションを確認
  - Linux 用 Windows サブシステム ディストリビューションがubuntuになっていなければ
    - wsl -s Ubuntu でサブシステム ディストリビューションをubuntuに変更する
  -

**Comment by haruki256** [comment]
プロジェクトの完成から、勉強メインになったため強制ではない。
